/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package kucharka.gui.dialogs;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import kucharka.api.CommentService;
import kucharka.gui.KucharkaFrame;
import kucharka.gui.comments.CommentsPanel;
import kucharka.impl.DBCommentServiceImpl;
import kucharka.model.Comment;
import kucharka.model.Recipe;

/**
 * Dialog obsluhující nový komentář
 * @author Jakub Josef
 */
public class AddCommentDialog extends javax.swing.JDialog {
    private CommentService commentService = new DBCommentServiceImpl();
    private Recipe recipe=null;
    private CommentsPanel commentsPane= null;
    private JLabel ratingPane = null;
    private JButton btnAllComments =null;
      
    public AddCommentDialog(KucharkaFrame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        setLocationRelativeTo(parent);
        commentsPane = parent.getCommentsPane();
        ratingPane = parent.getRatingPane();
        btnAllComments = parent.getAllCommentsButton();
        initComponents();
    }
    public AddCommentDialog setRecipeID(Recipe recipe){
        this.recipe=recipe;
        setTitle(recipe.getName());
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        commentAuthor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnAddComentDialog = new javax.swing.JButton();
        pnlRating = new kucharka.gui.dialogs.RatingPanel();
        lblError = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Přidat komentář ");

        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        txtText.setLineWrap(true);
        txtText.setRows(5);
        txtText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtText);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Autor:");

        commentAuthor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        commentAuthor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Text komentáře:");

        btnAddComentDialog.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnAddComentDialog.setText("Komentovat");
        btnAddComentDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddComentDialogMouseClicked(evt);
            }
        });

        lblError.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 0, 0));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlRating, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddComentDialog)
                                .addGap(9, 9, 9))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(commentAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel3)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblHeader)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(commentAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAddComentDialog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddComentDialogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddComentDialogMouseClicked
        if(!commentAuthor.getText().equals("") && !txtText.getText().equals("")){
            //pridame data
            Calendar c = Calendar.getInstance();
            commentService.addComment(new Comment(commentAuthor.getText(), txtText.getText(), (byte) pnlRating.getRating(),new Date(c.getTimeInMillis()),this.recipe.getId()));
            //aktualizujeme data na receptu
            commentsPane.setData(commentService.getComments(this.recipe.getId()));
            ratingPane.setText(new Float(commentService.getRating(this.recipe.getId())).toString());
            btnAllComments.setEnabled(true);
            this.dispose();
        }else{
            lblError.setText("Nevyplněny všechny povinné údaje!");
        }
    }//GEN-LAST:event_btnAddComentDialogMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComentDialog;
    private javax.swing.JTextField commentAuthor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblHeader;
    private kucharka.gui.dialogs.RatingPanel pnlRating;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables

}
