package kucharka.gui.dialogs;
import kucharka.api.CommentService;
import kucharka.impl.DBCommentServiceImpl;
import kucharka.model.Recipe;

/**
 * Dialog pro zobrazeni vsech komentaru
 * @author JaKoB
 */
public class ViewCommentsDialog extends javax.swing.JDialog {
    private Recipe recipe=null;
    private CommentService commentService = new DBCommentServiceImpl();
    /**
     * Creates new form ViewComments
     */
    public ViewCommentsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setResizable(false);
        initComponents();
    }
    public ViewCommentsDialog setRecipeID(Recipe recipe){
        this.recipe=recipe;
        setTitle(recipe.getName());
        pnlComments.setData(commentService.getComments(recipe.getId()));
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlComments = new kucharka.gui.comments.CommentsPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Všechny komentáře");

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout pnlCommentsLayout = new javax.swing.GroupLayout(pnlComments);
        pnlComments.setLayout(pnlCommentsLayout);
        pnlCommentsLayout.setHorizontalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnlCommentsLayout.setVerticalGroup(
            pnlCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnlComments);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private kucharka.gui.comments.CommentsPanel pnlComments;
    // End of variables declaration//GEN-END:variables
}
